services:
  app:
    image: server:1.0.0
    container_name: sancti-check
    build: 
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
    - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      database:
        condition: service_healthy
  
  database:
    image: mongo:latest
    container_name: ${DATABASE_HOST}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    build: 
     context: ./database
     dockerfile: Dockerfile
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: sancticheckdb
    volumes:
      - database-v:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 20s
volumes:
  server-v-node-modules:
    name: "server-v-node-modules"
  database-v:
    name: "database-v"
